### ISSUE TITLE
Desktop Automation Plugin breaks Windows 7 compatibility

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#140]
Enable/Disable switch in preferences should hard disable plugin to fix compatibility! Some research may be required!

## Todo
- [ ] Fix Windows 7 compatibility by hard disabling the Desktop Automation plugin

**Comment by kkerti** [comment]
I have removed now `win-title` and the `nutjs` desktop automation plugins. We should introduce them optionally.
