### ISSUE TITLE
Merge resizable panel container demo into main!

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#141]
- [x] Left and right panels can be resized
- [x] When closing left-panel by dragging it to w=0 panel tab selection should be cleared
- [x] When left-panel is closed and no tab is selected, drag-open opens empty panel (should select first tab automatically)
- [x] Tabs that should render h-full content now render incorrectly (please see image) 

![Image](https://user-images.githubusercontent.com/32985513/217821821-a3fd17be-f0ee-4a56-bb84-3c3e8f24dd3f.png)

**Comment by kkerti** [comment]
ok

**Comment by SukuWc** [comment]
QA failed, feature not release ready,  please check the updated acceptance criteria !

**Comment by kkerti** [comment]
New variable `$appSettings.leftPanelVisibity` introduced, to keep track of hidden tabs. Navigation works as usual, closing the pane sets the visibility to false on left panel and pulling the pane resize bar restores the last left panel state by changing the leftPanelVisibility to true.

Should be cleaned up when the new design is introduced.

**Comment by kkerti** [comment]
Default overflow hidden on split_pane css hides the action picker. Overwriting it helps in App.svelte's style block.,
