### ISSUE TITLE
Local block variable names and values become mixed up when a line is deleted

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#145]
![image](https://user-images.githubusercontent.com/74784772/214258283-8d19ba0b-52cc-4092-8ee1-d38882ba45ec.png)

After a line is deleted, only the variable name leaves the local block table, and the variable value side shifts up; leaving the whole table messed up in with mixed variable names and values.

**Comment by SukuWc** [comment]
Should also check global and self variable blocks, they most likely behave similarly!

**Comment by SukuWc** [comment]
It seems that it was only a display bug, fixed anyways!
