### ISSUE TITLE
What's the rational to delete comments on commit?

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#149]
I've read [in the documentation](https://grid-documentation.onrender.com/wiki/actions/code/comment) that it is by design that comments are deleted on a commit, but why is that? I guess it is to help stay within the 400 characters limits, but I find it also overzealous. I would leave to the developer to decide how to use that space. Complex behavior may be helpful to keep documented. Thanks.

**Comment by SukuWc** [comment]
We use a third party library to minify user inputted lua code to use less memory on the target device, unfortunately this minifier removes all comments as well. We tried to change this behavior but could not figure it out yet. I will see if we can put this on the roadmap for  one of the upcoming releases. Until then you can use the dedicated comment block from the action blocks!

**Comment by SukuWc** [comment]
Needs more work, but line comments work fine!
Block comments are converted to line comments to make life easier!

Works by converting line comments to global variable base64 strings to avoid being removed by minifier. Back conversion is also done automatically.

![Image](https://user-images.githubusercontent.com/32985513/218504774-bde8e9f6-639a-4b9b-985a-f45ee4a70784.png)
