### ISSUE TITLE
Feature request: please remember the open/close status of the blocks

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#150]
Every time I move from one element to another in editing a module and then go back to it, all modules are closed, and I need to open them back again. This is very inconvenient when I need to move quickly between elements to see how I implemented a custom feature. Thanks.

**Comment by SukuWc** [comment]
Hello, thanks for the request, we actually just implemented it last week, it is coming in the next release! If you have any more requests then feel free to open new issues here on github!
