### ISSUE TITLE
Login to user account

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#156]
User should be able to login to the user account. idToken and refreshToken is received from the server, which can be stored between sessions in the electron-store. All fetch request should have a `Authorization: Bearer TOKEN` header. Somehow sync should be doable between the server and editor, like a user updates it's profile data on the website, it should be visible in Editor as well. Or at least don't store such data between session, but reload them.

Define MVP feature set:

- [x] login to user account
- [x] store login info between sessions
- [x] refresh token upon expiration 
- [x] make re-usable `fetch` wrapper - get, post, patch, delete + headers
- [ ] make sure if no internet connection is present, app doesn't break
- [ ] change user name
- [ ] _sync data with server? server push if account changes? is there anything important?_

**Comment by SukuWc** [comment]
Make sure to add register button that openes intech.studio website to complete the registration form. For MVP itos ok to just open in system defult browser, later we might embed it into the editor...

![Image](https://user-images.githubusercontent.com/32985513/218511210-d2423301-c332-4520-bf37-bc0b16f96e29.png)
