### ISSUE TITLE
Right & Middle Panel UI update based on Figma design

### ISSUE THREAD

**Issue by bettyblack23** [intechstudio/grid-editor#173]
- [x] move to middle panel: '_active changes_';  _'config store',_ put under the three dot "menu" the _'clear '_ and engine buttons
- [x] middle panel: _'Pages'_ button design
- [x] right panel: _'UI Event'/'System Event'_ changer button placement and design
- [x] right panel: _'Events button design'_
- [x] right panel: _'Actions'_: grab cursor on action and 6 packs icon
- [x] right panel: delete selected element, element name redesign and info (tooltip)
- [x] '_active changes_';  _'config store'...classic view

**Comment by narayb** [comment]
![Image](https://user-images.githubusercontent.com/74784772/224320854-21c28db6-4d8c-4749-b50b-d8d78a8beec1.png)

Content layout while dragging

**Comment by narayb** [comment]
Updated UI looks ok, I have no access to the updated changelog, but based on own expectations and past experiences:
- top right looks too clean, there should be a divider between UI/System and the Events themselves
- top right Element Name still takes up way too much space for the utility it provides, suggest to hide it by default in preferences
- switching between UI/System has an animation that makes the bottom part of the UI fade in from the left/right, this looks weird, either change the animation or not let it move through the outer bounds of the UI
- opened Actions don't always remain open as if the act of opening them didn't register in the Editor and switching back and forth reveals that it forgot that you opened it, this is a bug
- opened Action colored stripes have been fixed, nice
- re-arranging the Action Chain feels good and works well, even if the box that you have to grab is a bit too small
- Pages moving to the middle feels weird, but works well in practice (windows size affects it and skews the Page buttons to the left from the middle, we should decide if it's good or not)
- removing the top bar from Editor made the both the right and left panels float and they are sticking out from the design of the other elements that for example have all rounded corners (sidebar buttons, floating buttons) page buttons also lack rounded corners
- in general some elements have rounded corners and some do not, this makes their combined appearance look all over the place - decide on a clean solution

In general, visual language is really messy and incoherent, functional usability is a bit better and of course there are some bugs to splat.

**Comment by narayb** [comment]
Press and Release block is broken visually.
If blocks and their kin are broken visually.
Special action blocks are broken visually.


![Image](https://user-images.githubusercontent.com/74784772/227245164-f740e75a-29f5-4bba-a9b1-0933e4e0f3b3.png)



![Image](https://user-images.githubusercontent.com/74784772/227245406-2b203e8e-e78b-42e5-ba50-cf19794340c3.png)



![Image](https://user-images.githubusercontent.com/74784772/227245621-2cb8f75b-52da-4019-bddf-fbacb79c8b4c.png)

**Comment by bettyblack23** [comment]
![Image](https://user-images.githubusercontent.com/61327809/227975027-87dcdce6-f270-45bd-92b1-56022dd1213a.png)

**Comment by bettyblack23** [comment]
2.0

![Image](https://user-images.githubusercontent.com/61327809/228861293-8a98b6db-13e6-46e7-b3e1-abb615187b0d.png)
