### ISSUE TITLE
Loading complex configurations with Profile load (usermade Seque or inhouse made RYK16 sequencers) crashes the module while trying to load the config.

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#188]
Loading complex configurations with Profile load (usermade Seque or inhouse made RYK16 sequencers) crashes the module while trying to load the config.

This shouldn't happen since if you have the same config recreated bit-by-bit on a module, then it can be copied without issue with the "copy all" and "overwrite" functions of Editor to another module. 

The issue probably lies with how fast Profile load tries to push the configuration to the module, and it's not a problem of running out of memory while the Grid module runs the profile itself.

This issue is important because it prevents the sharing of profiles, and causes false feedback (module crashes, suspected memory error/hardware error) about the profile when the user tries to load it onto a different module.

Check instant retrying (when storing a module, a logger message can be seen on the bottom of the screen) and timeout periods related to this issue.

**Comment by narayb** [comment]
[sequencers.zip](https://github.com/intechstudio/grid-editor/files/10967796/sequencers.zip)

Problematic profiles in archive.
