### ISSUE TITLE
Bug, ver. 1.2.31: editor interprets incorrectly the scientific notation of numbers

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#198]
If I write this while editing a code block:

<img width="193" alt="image" src="https://user-images.githubusercontent.com/303693/226168241-75498454-5252-4aa0-b2f0-5ab68d942f92.png">

... it is "interpreted" as a mathematical operation:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/303693/226168308-aa71d5b1-4351-4bcd-ab78-7e9bde2dfc8c.png">

**Comment by SukuWc** [comment]
I got in touch with the maintainer of the lua-minifier package, this is indeed a bug that we will try to sort out! Thank you for reporting!

**Comment by elsoazemelet** [comment]
This seems to be already patched in the newest release.
