### ISSUE TITLE
Feature request: remove most UX embellishments

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#237]
The novelty of all animations and embellishments in the UX is nice to see only for the first few minutes. If one is serious about programming the Grid, all those animations quickly become annoying, slowing a developer's workflow. May we have an option to kill them all? Thanks! 🙂

**Comment by kkerti** [comment]
Hi Giacecco,
We've streamlined some of our animations in the currently on-going sprint, making them smoother and less resource hungry. Please let us know what you think after the next release (v1.2.33). Also it would be great if you could point at areas, which you found specially annoying.
