### ISSUE TITLE
1.2.33: Huge usability fail - store button disappears after click

### ISSUE THREAD

**Issue by amkdev** [intechstudio/grid-editor#242]
Hey devs, it's a big mistake to remove buttons after user interaction. You can disable it (give it transparency, another colour whatever), but please never never remove a button after click! This causes confusion for users! A user interface is not an arcade game ... and the fact that after the store button disappears, the clear button jumps right under the mouse cursor … annoys me (as a frontend developer since 25 years) because this is in addition a dangerous situation for inexperienced users.

<img width="756" alt="grafik" src="https://user-images.githubusercontent.com/5300389/236507704-10a48d24-e211-4cd1-ac1a-0f5eaf363a46.png">
<img width="804" alt="grafik" src="https://user-images.githubusercontent.com/5300389/236507805-7d6b57b7-a0fb-419b-a1e3-3e17d74dfb02.png">

**Comment by kkerti** [comment]
The idea behind this change was to only show the Store button if there are any changes made to the configuration. Without config changes, we did not want to show a store button automatically: a profile upload or session profile save button could be in focus then. In short, we wanted to aim for less call to action buttons on the UI.

We're very soon our way to superbooth23, but we'll discuss this further with devs.

**Comment by kkerti** [comment]
Ok, we'll fix. this.

@elsoazemelet show all the buttons: store, clear, discard. Also change the "ENABLED/DISABLED" to the new icons.
