### ISSUE TITLE
Enable Tray from Preferences

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#250]
If tray is not enabled turn the editor to fully closed. If no plugin is present, we can do this, so re-appear, disconnect of modules may get more straight forward.

**Comment by SukuWc** [comment]
Create setting in preferences to enable/disable tray!

**Comment by elsoazemelet** [comment]
Create setting in Preferences with a checkbox to enable tray.
Store its value persistently in a store.

Default behaviour: tray is disabled
Expose tray creation method to frontend, and modify app startup in main.ts and close buttons event handler accordingly.
See: firmware download
