### ISSUE TITLE
[MEGA] Proper enabling/disabling for plugins

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#290]
- [x] Github Actions CI/CD
- [x] One plugin for all plaforms or three plugins for three platforms

## Plugin tech
- Internal plugins are rebuild when editor is being built
- Editor project contains pluginlis with list of included plugin repositories
- Duplicate dependecies must be cleard when building plugins basted on editor's package-lock.json

### Active Window
Phase 1: trigger page change when a main application window changes.
Phase 2: trigger page change based on regex for sub floating windows, like plugin views
Phase 3: connect with browser tabs?

![Image](https://user-images.githubusercontent.com/47832952/247579505-877bcbe7-e918-483d-bcb8-9b321b301f83.png)

**Comment by danim1130** [comment]
Preferences: single html file with everything bundled, js interface to communicate.

**Comment by danim1130** [comment]
## Visual Studio Code
![image](https://github.com/intechstudio/grid-editor/assets/8405234/b17e5773-7eff-4a2c-87a6-6f0d1a8157dc)
![image](https://github.com/intechstudio/grid-editor/assets/8405234/8e6d9f9c-6a02-4d8b-8b14-e4b231130e44)
![image](https://github.com/intechstudio/grid-editor/assets/8405234/7be9556b-14fd-4fc7-833a-55225dc2c3dc)

## Android Studio
![image](https://github.com/intechstudio/grid-editor/assets/8405234/77bf0e29-ff86-42ee-a267-7f4356124cdd)
![image](https://github.com/intechstudio/grid-editor/assets/8405234/26ffe830-6201-4a7b-82c1-e7c699a442c6)

## Firefox
![image](https://github.com/intechstudio/grid-editor/assets/8405234/59399017-5458-40b0-b106-05eab5bf613e)
![image](https://github.com/intechstudio/grid-editor/assets/8405234/e5ef16ca-d957-439c-b978-a8af9ec49986)

## Notepad++
![image](https://github.com/intechstudio/grid-editor/assets/8405234/768c71db-c486-49fb-96c0-c6d2c84a423c)
![image](https://github.com/intechstudio/grid-editor/assets/8405234/d9f98354-8cdf-404e-bd9e-69815b8f6a4a)
