### ISSUE TITLE
preset browser seem to always look for preset in the default path, ignoring settings

### ISSUE THREAD

**Issue by nodens** [intechstudio/grid-editor#356]
Hi, I think I found an interesting bug in the linux version: the preset browser seem to always look for preset in the default path, ignoring settings.

What I did:
- I set up a preset folder as ~/.config/intech/grid-userdata, this folder being a symlink to ~/<my own, nondefault path for grid-userdata>. I used that because it follows freedesktop.org logic for config files.

- I  then downloaded the preset, and whle the json files where there, the editor would always complain about the presets not being present.

- I changed to the default directory, downloaded again, I could see the presets

- I changed back to my custom directory, could still see the presets

- I deleted the default directory: no more preset in the browser… 

- Saving the session preset always saves it in the default folder, too.

For now I worked around it by setting up a symlink in the default location to my desired location, which make the browser happy (and saving happening in the configured place).

Thanks!

**Comment by SukuWc** [comment]
Thanks for reporting the issue, we will look into this!

**Comment by SukuWc** [comment]
In the latest release we migrated to using Profile Cloud browser for both online and offline profiles! Please check it!
