### ISSUE TITLE
When selecting an Action Block selection marker is not persistent after making selection

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#359]
Selection highlight only visible on mouseover.
![image](https://github.com/intechstudio/grid-editor/assets/74784772/1eb002f8-b376-4e38-9d29-0a2b2765922d)
But doesn't stay "on" even after confirming selection with a click.
![image](https://github.com/intechstudio/grid-editor/assets/74784772/c7159fc6-dfdc-4ae7-8781-87ce883dc2dc)

Expected behavior should be that the selection stay visible after the selecting click, allowing for the "click the Action you want to add then click Add Action" workflow.

**Comment by SukuWc** [comment]
Already fixed
