### ISSUE TITLE
User request: Disable all animations from perferences

### ISSUE THREAD

**Issue by elsoazemelet** [intechstudio/grid-editor#375]
Add option to disable all animations in preferences.
Connect this option with the svelte transitions and css transitions.
These are:

- transition-<something> in tailwind
- transition:<something>={...} in svelte
- in/out:<something>={...} in svelte
- anything that uses something from "svelte/transition"
- etc. be creative

**Comment by SukuWc** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
