### ISSUE TITLE
Grid editor error: module drops out with "Configuration: Unknown device!" error.

### ISSUE THREAD

**Issue by Ropedragon** [intechstudio/grid-editor#380]
Similar to thread #358, grid editor drops modules after roughly 30 seconds and states unknown device in inspector console. Device still sends MIDI. Cannot see device in editor unless I unplug the module and then plug it back in and it doesn't always succeed.

Dropout seems to occur after moving faders/encoders sufficiently. "Undefined" counter goes up with each interaction (see attached image).

Operating system is Windows 10.

![image](https://github.com/intechstudio/grid-editor/assets/143750346/e184a18f-c5b8-4e61-a336-7db7c8b84168)

**Comment by danim1130** [comment]
Issue is fixed with a new firmware update shipped with Grid Editor v1.2.42. Thanks for the report!
