### ISSUE TITLE
Explicitly discourage or allow expressions in regular action block input fields

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#411]
Currently it's not trivial if we can use expressions in action blocks like in the image below. Also what if the below *magically works*, but an other expression with parenthesis doesn't?

<img width="507" alt="image" src="https://github.com/intechstudio/grid-editor/assets/47832952/0b30a4d6-8383-449b-8336-a475e7a65726">

**Comment by elsoazemelet** [comment]
Investigate why it does not work, because it should. Fix the humanizer/minimizer usage.
