### ISSUE TITLE
Allow moving the control surface in the layout to different positions

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#445]
Previously with the `panzoom` library, moving the control surface in the center layout area was possible. This feature is cool to create blog - marketing - other content, where the framing of the configuration can be changed.

**Comment by elsoazemelet** [comment]
Implement it when the new control surface design is defined.

**Comment by SukuWc** [comment]
This state should not be persistent for now.
When runtime.length==0 then reset layout
