### ISSUE TITLE
Action Block: Mouse button throws Editor error

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#492]
Repro:
- add a mouse button action to an action chain
- enter 1 into the state
- get an error.
<img width="1507" alt="image" src="https://github.com/intechstudio/grid-editor/assets/47832952/39d8ad64-7ca2-4a53-b557-13bfa7d7804d">

**Comment by elsoazemelet** [comment]
On stable this no longer seems to be an issue
