### ISSUE TITLE
Delete feature is currently broken - Editor 1.2.46 

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#507]
When deleting an action block and then storing the changes, the block appears deleted but after a reconnect, it will stay in Grid memory and show in Editor as well, as if the deletion never happened.

**Comment by SukuWc** [comment]
Could not reproduce

**Comment by narayb** [comment]
Did you try it on 1.2.47?

**Comment by kkerti** [comment]
@narayb @SukuWc checked on today's stable (almost release v1.2.48), could not reproduce on EF44 D51 nor on PBF4 ESP.

**Comment by narayb** [comment]
Retested and could not repro. Suspected FW bug on ESP32 units.
