### ISSUE TITLE
Grid Editor 1.2.47 crashes every time when quitting

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#526]
To reproduce:
1) start Grid Editor
2) quit 😄

I'm on macOS 14.1.2, M1 Pro.

**Comment by kkerti** [comment]
@giacecco could you please confirm if it's still bad on version v1.2.28? Made adjustments to background process lifecycle handling and it to me (on Mac M1 Pro Ventura 13.4.1), problem seems to be resolved.

**Comment by giacecco** [comment]
It looks ok now @kkerti , thanks!
