### ISSUE TITLE
Package sidepanel init causes runtime error

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#533]
üres userdata mappával ezt kapom package page nyitásakor vagy refresh gomb nyomásakor

![Image](https://github.com/intechstudio/grid-editor/assets/32985513/376d3a59-59ab-482a-839c-b45bf79b88a6)

**Comment by SukuWc** [comment]
Other issue when trying to enable a package: 

![Image](https://github.com/intechstudio/grid-editor/assets/32985513/f04b9972-0fc7-410e-92bf-9c445a962b12)



![Image](https://github.com/intechstudio/grid-editor/assets/32985513/c14c8eb7-9389-42b1-b8a6-1785a251752f)

**Comment by danim1130** [comment]
Én attól félek, hogy ez nem az üres userdata mappa miatt van, de jó lenne tudni, hogy hogy jöt elő ez a hibaüzenet
