### ISSUE TITLE
ResizeObserver loop error handling is missing

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#554]
This happened, when the window was resized.

Add proper catch mechanism for error handling on resize observer failure.

![image](https://github.com/intechstudio/grid-editor/assets/47832952/675245ab-e080-4929-b38c-83dcc66e5f39)
![image](https://github.com/intechstudio/grid-editor/assets/47832952/aaf16ad0-6014-46cc-8c5e-2a25f063c3a9)

**Comment by SukuWc** [comment]
use:watchResize={resize}
