### ISSUE TITLE
Code Block of Push & Rotate L R improvement

### ISSUE THREAD

**Issue by tyhts0829** [intechstudio/grid-editor#570]
Code Block of Push & Rotate L R is below
if (self:button_state() > 0 and self:encoder_state() < 64) then
elseif (self:button_state() > 0 and self:encoder_state() > 63) then
elseif (self:button_state() == 0 and self:encoder_state() < 64) then
else
end

but I think it should be
if (self:button_state() > 0 and self:encoder_state() == 63) then
elseif (self:button_state() > 0 and self:encoder_state() == 65) then
elseif (self:button_state() == 0 and self:encoder_state() == 63) then
elseif (self:button_state() == 0 and self:encoder_state() == 65) then
else
end

**Comment by SukuWc** [comment]
Can you please explain the proposed changes and the effect it has?
