### ISSUE TITLE
Stable Nightly Editor freezes and module disconnects when sending too many messages with a certain profile

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#580]
## Steps to reproduce
- load profile Seque 1.3 on an EN16 (tested on D51, FW v1.2.29)
- turn the speed of the sequencer up by rotating the bottom right encoder clockwise
- module will disconnect from Editor and throw that error

![Pasted image 20240130151028](https://github.com/intechstudio/grid-editor/assets/74784772/2ebe74cb-34e7-4b09-be52-9a924271f839)

(on release version Editor 1.2.48 the same steps only produce disconnects with instant reconnects)

**Comment by Greg-Orca** [comment]
**Issue:** Blinking stops when MIDI value reaches or exceeds 248, does not blinks thereafter.

**Repro:**
1. Increase MIDI value gradually until 248 or higher.
2. Notice blinking stops.
3. Decrease MIDI value.
4. Blinking does not resume.

**Comment by narayb** [comment]
> **Issue:** Blinking stops when MIDI value reaches or exceeds 248, does not blinks thereafter.
> 
> **Repro:**
> 
> 1. Increase MIDI value gradually until 248 or higher.
> 2. Notice blinking stops.
> 3. Decrease MIDI value.
> 4. Blinking does not resume.

This is an issue with the sequencer itself, not with Editor. The sequencer is a community-built one, so we should contact the dev with the bug. Project repo can be found here: https://github.com/mattcoffyn/Seque-MIDI-Sequencer-for-Grid.
