### ISSUE TITLE
Virutal module bug: Element selection dropdown in configuration panel causes runtime error

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#582]
Tested on current stable branch!

![Image](https://github.com/intechstudio/grid-editor/assets/32985513/a34aae19-535f-45a2-869a-487ad085a05c)

**Comment by elsoazemelet** [comment]
Fixed on bug/MeltSelect, possibly previous changes on this branch solved this bug. After merging, it should solve it automatically.
