### ISSUE TITLE
Bug: saving a preset in the Profile Cloud does nothing

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#607]
Hi All, I am a fan, and if you check my record, I own more Grid elements than - I guess - anyone else 😄 At the same time, this gives me cold sweats when your software fails or is not robust enough to be trusted. The Profile Cloud, for example: great idea in principle, quite poor UI implementation in my opinion, since ever.

I've been waiting to write about this for a very long time, to give you some slack, but today I really need to share what I observe, because the Grid Editor has become unusable. 

My problem, in short, is that the UI is so bad that I can't tell the difference between when it works and when it does not! And when some obvious functionality is missing, I can't tell if it really doesn't exist or it is hidden somewhere. Do you ever have that feeling with other software? I don't.

A few examples using version 1.2.48, after logging in. My Intech Studio username is the same as in Github.

a) how is it possible that there is no way to see just _my own_ presets?

b) how is it possible that I can't filter presets _by username_?

c) how is it possible that when I click on "Save" for a preset, nothing happens? I see a few popups at the bottom of the screen (preparing... ready... imported successfully...), the filter of the presets browser resets, but nothing else! the Editor does not ask me anything about what I am saving, the name of the preset, its description etc., where did it go?!?

d) and because I do not know where it did go, I cannot load it back to another of my Grid modules.

😭

**Comment by giacecco** [comment]
I have tried again and have more information. It seems that saving (today? was it like that yesterday, too?) creates a "New [module name] config" profile that - because the preset browser resets as described above - is not clearly visible and gets hidden somewhere down in the long list of presets.

One day when Intech Studio will be successful, those lists of presets will be super long. It doesn't make sense that the UI behaves like this. There should be a toggle that enables the user to see only their own presets vs the whole community's (suggestion (a) above).

**Comment by SukuWc** [comment]
Hi, we are in the process of reworking the profile cloud browser. We chose VS Code's extension browser as a design reference. There will be top-level categories for configurations: My configs, Recommended configs and Community configs. You can expect incremental improvements in the profile cloud UX in the following weeks!

Thank you for the detailed reports!
