### ISSUE TITLE
Bug: Grid Editor suggests to login when logged in already

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#608]
On 1.2.48. To reproduce:

- start Grid Editor and login
- quit Grid Editor
- start Grid Editor
- in the bottom left corner of the UI, there's a box saying "login to save and browse your profile"
- click on the "login" button
- the UI tells you that you are already "Signed in as:..."

Note also that if you logout and login again, the box disappears.

**Comment by SukuWc** [comment]
We are looking into this!

**Comment by SukuWc** [comment]
Thank you for the patience, fix will come in the next release
