### ISSUE TITLE
Feature request: make better use of the Profile Cloud pane

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#610]
Version 1.2.48. This part at the top of the Profile Cloud window uses a lot of space without necessarily being useful. Once the user has read it once, it is just a waste of screen estate.

<img width="602" alt="image" src="https://github.com/intechstudio/grid-editor/assets/303693/9bfda982-51ee-499b-81ff-3e51028eae0f">

Also, it is not intuitive for the user to remember the difference between "profile" and "preset" I need to read your description every time. I would rather suggest using the drop-down list better. It could say "Profile - Whole configuration" and "Preset - Current module". 

<img width="545" alt="image" src="https://github.com/intechstudio/grid-editor/assets/303693/f69824de-45b1-41fc-8c33-d9e703175f81">

**Comment by SukuWc** [comment]
Please check the new version that we released this week. This part of the UI is fully reworked, I hope you will like it! If you have any more ideas to share, please do not hesitate to create a new issue! Thank you for your continued support!

Cheers!
