### ISSUE TITLE
Tooltips appear not where they are supposed to when window is maximized.

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#62]
![image](https://user-images.githubusercontent.com/74784772/151986048-90ba237d-70f3-4a9b-8be7-4ca711d572c5.png)

Tested on 1.2.13, Windows 10.

When moving the cursor over elements with tooltip messages, the messages appear at the lefternmost part of the menu instead of apprearing at the cursor location.

**Comment by SukuWc** [comment]
fixed since v1.2.2x
