### ISSUE TITLE
Tooltips disappear after clicking, active bug on both release and nightly stable

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#629]
For some reason each Editor tooltip disappears after clicking on the tooltip questionmark after hovering it.

![tooltip](https://github.com/intechstudio/grid-editor/assets/74784772/9f8c3739-af68-4346-9315-47feea1f6754)

Expected behavior should be that the tooltip stays visible, regardless of clicking until the hover lasts.

**Comment by SukuWc** [comment]
Also z-indexing is not perfect
