### ISSUE TITLE
Commenting out Grid functions, closing the code editor and then opening it again changes the functions to shortname versions - Editor v1.2.49 

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#637]
Here the MIDI send function got reduced to the shortname gms function:
![kép](https://github.com/intechstudio/grid-editor/assets/74784772/157ee2d0-6569-4a31-9821-bce83fe8c5c3)

**Comment by elsoazemelet** [comment]
- [x] Fix it to make it work with block comments

**Comment by elsoazemelet** [comment]
- [x] clean up string operations
- [x] unified algorithm for code zipping and unzipping
