### ISSUE TITLE
Context menu behavior

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#653]
Context menu should match how highlighting works in Windows

![windows_selection](https://github.com/intechstudio/grid-editor/assets/74784772/9615d534-ed87-4001-8124-cbbbf053fd07)

Context menu should disappear when clicking anything in profile cloud or Editor window loses focus.

**Comment by narayb** [comment]
![jumping_context](https://github.com/intechstudio/grid-editor/assets/74784772/e99e1469-78d8-402e-a2cb-3705d916f250)

Opening Context Menu makes the whole Editor window jump around.

**Comment by elsoazemelet** [comment]
- [x] Fix context menu closing when focusing iframe
