### ISSUE TITLE
Action toolbar names should all be unique

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#654]
![kép](https://github.com/intechstudio/grid-editor/assets/74784772/206f5570-6e00-4822-8ca5-1fe45ba501f1)

Change the Copy of Elements to 'Element Copy' etc. so that they do not match.

Remove category names.

![kép](https://github.com/intechstudio/grid-editor/assets/74784772/c782bccf-5742-4bf9-baf0-ba0b2f8d541a)

Same textname should appear in context menu.

**Comment by SukuWc** [comment]
- Stretch goal: check different hover colors
