### ISSUE TITLE
Bug: grid components' lights flashing while Grid Editor is running 

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#670]
I had never noticed this before before yesterday. I'm using Grid Editor "production 724942 2024-03-19" and all my grid modules are up to date with the latest firmware.

When my grid is connected using USB (a big one, 4 x 2) and Grid Editor is running, the lights on some (not all) of my connected grid components flash. It is not rhythmic, I can't understand if they represent anything. If I close Grid Editor, the flashing stops and the lights go back to representing what they are supposed to represent.

As an addition to that, while the Grid Editor is running and the flashing is happening, sometimes some of the components stop being shown on screen, like if I had disconnected them, though they are still working (my DAW receives their signals)> When that happens, the flash stops, too. Stopping and restarting Grid Editor does not change the situation.

Thanks!

**Comment by SukuWc** [comment]
Can you confirm that this issue was fixed in the latest release?
