### ISSUE TITLE
Grid Editor keeps asking me to login when I am logged in already

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#674]
Whatever I do, when I start the Grid Editor (using version "production - 7274942 2024-03-19") I always see the popup at the bottom saying "Login to save and browse your profiles."

I then click on the login button, and it tells me that I am "Signed in as: [my email]". I click on close and the popup asking me to login is still there.

If I logout and login again, the popup disappears... until I restart the Grid Editor again.

Thanks!

**Comment by SukuWc** [comment]
Thank you for the report, we will take a look at this!
