### ISSUE TITLE
Fixes for Package Manager

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#732]
**2024-05-21**

- Allow package manager to run without internet
   - When Editor starts without internet, the package manager can hang in "Restarting package manager..." state
   - When the internet connection is lost WHILE Editor is running, make sure that package manager continues to work
- Package manager should handle the case when a package is deleted from the `grid-userdata` folder, but the package name is kept in the persistent settings
- When there is an unhandled error in a package's code, it should be caught and shown in the Editor. A wrong package code should never render Editor unresponsive. 
- Maybe show an indicator when a package is healthy? API for errors / warnings in the package? Health check?
- Handle when package cannot start due to missing `node_modules` or other issues.
- The package release check query to GitHub can result in rate limiting, which then fails at a `.find()` function.
- The package manager can spawn node processes which cannot be stopped with ctrl+c in terminal. It has to be specifically killed, or the whole Electron.exe has to be stopped. Consider killing Editor's spawned node processes on electron app exit / restart as a clean up step.

**2024-05-23**
- File / package watcher to restart package manager automatically WHILE in development mode.

**Comment by kkerti** [comment]
![image](https://github.com/intechstudio/grid-editor/assets/47832952/48471692-d194-4df1-b244-89d13f5be115)
@danim1130 please check this continuous stream of mixpanel requests in relation with package manager.

**Comment by kkerti** [comment]
![image](https://github.com/intechstudio/grid-editor/assets/47832952/df62b2d4-3090-49d9-8294-6478d04dff43)
This error comes up in development.

**Comment by SukuWc** [comment]
Pipe package's console.log through to editor's console.log
