### ISSUE TITLE
Grid layout renderer freezes when adding module that closes a circle, tested on 1.2.53

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#740]
Reproduced on win10 and macos.
Happens with 4 and 6 modules.

Throws error when it happens, Editor requires restart.

![kép](https://github.com/intechstudio/grid-editor/assets/74784772/cc4bacca-4502-4d24-87fb-ecf4447da60b)

**Comment by SukuWc** [comment]
@narayb Can this be reproduced in latest release?

**Comment by narayb** [comment]
@SukuWc Tested and not able to reproduce the bug on 1.3.3 anymore. This issue can be closed.
