### ISSUE TITLE
Controller scaling introduces spaces when below 100%

### ISSUE THREAD

**Issue by danim1130** [intechstudio/grid-editor#747]
![image](https://github.com/intechstudio/grid-editor/assets/8405234/edf6aca8-ed38-4c42-82e6-1a1cf24f98d4)

Sometimes when reconnecting modules, they are shown in the original scale:
![image](https://github.com/intechstudio/grid-editor/assets/8405234/0da9d3b9-e710-4aea-a298-4f7cf6c6487f)

Seems to be connected to disconnecting and reconnecting modules at larger scale, then scaling back, doesn't happen at start-up.

![image](https://github.com/intechstudio/grid-editor/assets/8405234/f5e35c9c-6c7f-4904-8576-fae112f3d48c)

**Comment by SukuWc** [comment]
Could not reproduce
