### ISSUE TITLE
[Feature Request] Show commercial MIDI channel under MIDI block

### ISSUE THREAD

**Issue by Greg-Orca** [intechstudio/grid-editor#763]
Most people get confused by our MIDI channel numbering. It would be great if we write the corresponding MIDI 1-16 channel numbering under the MIDI channel input.

<img width="343" alt="Screenshot 2024-07-01 at 12 11 31" src="https://github.com/intechstudio/grid-editor/assets/88966111/92e9fdd2-01d1-4b47-b3b1-17e98c99388e">

**Comment by SukuWc** [comment]
Ok, let's do this! @elsoazemelet 

0 -> 1
1 ->2
....
15->16
