### ISSUE TITLE
Discard element is sometimes unreliable

### ISSUE THREAD

**Issue by elsoazemelet** [intechstudio/grid-editor#776]
Reported by bálint:

In testing, the Discard Element sometimes failed to discard changes on Virtual modules.

Issue could be reproduced by loading the 'Loopy Pro Controller v1.3' Profile on a virtual EN16 and then trying to copy and overwrite encoders. When trying to discard the overwrites, they would remain in all cases active. Only discard all would get rid of these.

**Comment by Greg-Orca** [comment]
Discard function doesn't work immediately.

1. Change an action block.
2. Try to discard it.
Issue: Discard button is inactive and only works on the module page.
