### ISSUE TITLE
In the new mode action blocks, when using relative mode, setting min max doesn't make sense

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#791]
Either be able to make your own relative mode with the min-max when set to relative mode, or disallow activating the option when relative mode is active.

**Comment by SukuWc** [comment]
What is the behavior with the current implementation? 
Does -100 to 100 relative mode center on 0?
What control elements were tested?

**Comment by Greg-Orca** [comment]
- When the encoder is in _relative mode_ and the min/max values are changed, it sends out the middle value.
❓In _relative 2's comp_ mode, it alwas sends the values  1 and 127, and the min/max changes are not responsive

**Comment by Greg-Orca** [comment]
- When the encoder is in _relative mode_ and the min/max values are changed, it sends out the middle value.
- ❓In _relative 2's comp_ mode, it alwas sends the values  1 and 127, and the min/max changes are not responsive

<img width="595" alt="Screenshot 2024-08-28 at 14 36 37" src="https://github.com/user-attachments/assets/63599f93-525b-48fa-81f4-66863e2085de">
<img width="595" alt="Screenshot 2024-08-28 at 14 36 21" src="https://github.com/user-attachments/assets/f5b46687-25fe-411b-8a7f-1ebaeb55fbb3">
