### ISSUE TITLE
Typo in mode block

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#792]
![kép](https://github.com/user-attachments/assets/82964c8c-6bda-4d70-8dce-74ed32eddbfc)
 
Sensitivity

**Comment by Greg-Orca** [comment]
In Endless Mode input fields, "Encoder" should be changed to "Endless."
<img width="1013" alt="endless_mode" src="https://github.com/user-attachments/assets/ef9c9967-3297-40c3-bc42-78b8867c3a3a">
