### ISSUE TITLE
The Grid Editor freezes after clicking "What Happened" on a Missing Action Block message.

### ISSUE THREAD

**Issue by Greg-Orca** [intechstudio/grid-editor#795]
Repro:
1. Create a profile using the latest version of the Grid Editor.
2. Switch to an older version of the Grid Editor where the action block does not exist.
3. Observe the Missing Action Block message.
4. Click on the "What Happened" link.

Result:
The Grid Editor becomes unresponsive after clicking on "What Happened."

This issue is significant because users can switch between different versions (desktop and web) that are not in sync.

<img width="1042" alt="Screenshot 2024-07-29 at 14 46 17" src="https://github.com/user-attachments/assets/3594f094-b971-4dc5-a174-25cb5e43cb7a">

**Comment by SukuWc** [comment]
Ceck all questionmark based tooltips!

**Comment by elsoazemelet** [comment]
This seems to be not present in the current developer version
