### ISSUE TITLE
Visual settings under General settings

### ISSUE THREAD

**Issue by Greg-Orca** [intechstudio/grid-editor#819]
Certain settings are incorrectly categorized as Developer settings. These should be moved to General settings as they are more related to visual preferences.

- Scale UI
- Colorful toolbar
- Show PCB

**Comment by oemsysadm** [comment]
A +1 for selective UI scaling, maybe a 100-400% slider. I'm on a very large 4k monitor on Linux, and the UI is still nearly unusable.
