### ISSUE TITLE
Enhance Module Page Navigation (zoom and move)

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#839]
The current module page lacks the ability to move and zoom in/out. Adding these features would address the issue of modules being covered by other elements.

**Suggestion:**
- Implement drag-and-drop functionality to move modules within the page.
- Provide zoom controls for adjusting the module view.

**Expected Impact:**
 Improved usability and better visibility of modules, leading to a more efficient user experience.

![Image](https://github.com/intechstudio/grid-editor/assets/88966111/43749386-6b0d-4118-a1bd-3084545af022)

**Comment by Greg-Orca** [comment]
- [ ] bug: Editor freezes when opening Preferences
