### ISSUE TITLE
User submission: Troubleshoot firmware connection leads to broken URL

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#844]
Relaying user issue submission, the page linked under bootloader enumeration leads to no end.

Update underlying link.

https://discord.com/channels/761513181696098335/1295409488907472976

**Comment by SukuWc** [comment]
@kkerti please provide new url

**Comment by SukuWc** [comment]
Fixed on stable

**Comment by kkerti** [comment]
I have also checked the other links like `DOCUMENTATION_MAINTENANCE_URL`, they all should work now as excepted.
