### ISSUE TITLE
Default MIDI monitor shows gibberish values when sending MIDI from 7th element of a module

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#846]
![midimon_bug](https://github.com/user-attachments/assets/b8125f1f-4a56-4ca2-a8f3-e863754a682d)

**Comment by elsoazemelet** [comment]
- [ ] FIX SENDER IN MIDI MONITOR
- [ ] fix hi-res nprn value
- [ ] check grid sync (code block, checkboxes, etc.)
- [ ] midi monitor should be derived store of debug stream
- [ ] move derived store to MIDIMonitor 
- [ ] Update locals on runtime change
- [ ] Add min/max width combobox suggestion
- [ ] Remove "smart" resetting of min/max and sensitivity in setting blocks
- [ ] Re-fix setting blocks
