### ISSUE TITLE
Mode Block Sensitivity option breaks the block.

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-editor#848]
Repro by adding a Mode block and then enable sensitivity setting without enabling min/max setting.

Reproduced on both encoder and endless blocks.

![modeblock_sens_bug](https://github.com/user-attachments/assets/9391c9bd-2c59-4147-96f6-6b43a27bc666)

**Comment by SukuWc** [comment]
- [x] Button mode mi/max does not dispatch
