### ISSUE TITLE
Element name freezes Editor

### ISSUE THREAD

**Issue by Greg-Orca** [intechstudio/grid-editor#868]
When an "Element Name Block" is added to an element then switching between elements causes the editor to freeze and become unresponsive. Additionally, the "Element Name" is not displayed when switching back to the element.

**Repro:**

1. Add an "Element Name Block" to an element.
2. Rename Element Name. 
3. Switch to another element.
4. Switch back to the original element.
Editor freeze

**Comment by SukuWc** [comment]
Please check on stable branch if issue still exists!
