### ISSUE TITLE
Profile Cloud Window Height Issue on macOS

### ISSUE THREAD

**Issue by Greg-Orca** [intechstudio/grid-editor#876]
The Profile Cloud window does not render correctly on macOS, resulting in an incorrect height

https://github.com/user-attachments/assets/6510344f-2761-4878-b74e-05246d2df08d

<img width="300" alt="Screenshot 2024-12-10 at 15 40 58" src="https://github.com/user-attachments/assets/233861ce-d4fb-4354-927d-cbb587784389">
<img width="300" alt="Screenshot 2024-12-10 at 15 41 10" src="https://github.com/user-attachments/assets/c0e5fdd1-2f5d-43dd-be28-4405fc96098b">

**Comment by narayb** [comment]
All of the above issues are present on Windows as well.
